### ISSUE TITLE
To elaborate on Abstract section

### ISSUE THREAD

**Issue by shujingliew** [edi3/edi3-icl#19]

**Comment by shujingliew** [comment]
To add the following **bold** words in the Abstract paragraph, and perhaps replacing “Message API” with protocol:

There is no expectation that a single uber-ledger supports all G2G transactions. A specific ledger may service as few as two countries and may be limited to a single process (eg certificates of origin) or may service multiple countries and multiple processes **(e.g. certificates of origin + certificates of non-manipulation)**. Therefore this specification supports the use of multiple different distributed ledgers (both public and private) by defining a standardised **protocol** that allows users within a jurisdiction to interact with multiple ledgers via a simple **application** interface.

This document uses Certificates of Origin **and Certificates of Non-manipulation** as the guiding use case for the initial specification, however it is intended that the Inter Customs Ledger **(ICL)** should be generic and allow for the transfer of any shipment related documentation between authorised agencies.

**Comment by onthebreeze** [comment]
Accepted & implemented
