### ISSUE TITLE
To clarify whether Certifying Body (under Glossary) includes Government?

### ISSUE THREAD

**Issue by shujingliew** [edi3/edi3-icl#20]

**Comment by monkeypants** [comment]
My understanding was that a certifying body *could* be Government, but is *not necessarily* Government.

For example, Government may "delegate" authority to an organisation (such as a Chamber of Commerce) to issue certificates. In this situation, the Certifying Body is not Government (although Government is indirectly responsible).

Is that what you meant by your question? I'd be happy to draft an edit along those lines if that would help.

**Comment by shujingliew** [comment]
Yes, I think would be appropriate to include “Government” Body into the paragraph. For your consideration.

**Comment by monkeypants** [comment]
@onthebreeze FYI, I'll make a PR with this suggested edit.

**Comment by onthebreeze** [comment]
Suggestion accepted and Doc updated
